In [ ]:
print("hello this is first tesxt on google collab!")

hello this is first tesxt on google collab!


In [ ]:
!nvidia-smi

Wed Jan 29 11:11:16 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [ ]:
import torch
import pandas as pd
import numpy as np
print(torch.__version__)

2.5.1+cu121


## Introduction to Tensors

### Creating tensors

PyTorch tensors are created using `torch.Tensor()` =https://pytorch.org/docs/stable/tensors.html

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
# Get tensor back as python int
scalar.item()

7

In [ ]:
#Vector
vector =  torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
Matrix = torch.tensor([[7,8],
                      [9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
Matrix.ndim

2

In [ ]:
Matrix[1]

tensor([ 9, 10])

In [ ]:
Matrix.shape

torch.Size([2, 2])

In [ ]:
# Tensor
Tensor = torch.tensor([[[1,2,3],
                       [3,6,9]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9]]])

In [ ]:
Tensor.ndim

3

In [ ]:
Tensor.shape

torch.Size([1, 2, 3])

In [ ]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9]])

###Random tensors

In [ ]:
# Create a random tensor of size(3,4)
random_tensor = torch.rand(2,3,4)
random_tensor

tensor([[[0.3933, 0.7319, 0.4325, 0.9946],
         [0.8188, 0.7991, 0.4654, 0.1816],
         [0.8986, 0.4624, 0.6740, 0.5830]],

        [[0.6747, 0.8772, 0.9910, 0.7549],
         [0.4995, 0.9689, 0.3014, 0.8336],
         [0.2851, 0.7691, 0.6763, 0.0703]]])

In [ ]:
random_tensor.ndim

3

In [ ]:
# Create a random tenso with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) # height, width, colour channels(R,G,B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and Ones

In [ ]:
  # Create a tensor of all zeros
  zeros = torch.zeros(size=(3,4))
  zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros*random_tensor

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
 ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tesnors and tensors-like

In [ ]:
# Use torch.range()
# torch.range(0,10)
# torch.arange(0,10)
one_to_ten = torch.arange(start = 1,end = 111, step = 4)
one_to_ten

tensor([  1,   5,   9,  13,  17,  21,  25,  29,  33,  37,  41,  45,  49,  53,
         57,  61,  65,  69,  73,  77,  81,  85,  89,  93,  97, 101, 105, 109])

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0])

###Tensors datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:
1. Tensors not right datatype # what is the datatype of the tensor)
2. Tensors not right shape # what device is your tensor on
3. Tensors not on the right device # wether or not to track this tensors operation


In [ ]:
#Float datatype
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

###Getting information from tesors
1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. TEnsors not right shape- to get shape from a tensor, can use `tensor.shape`
3. Tensors not on th right divice- to get device from a tensor,canuse `tensor.device`

In [ ]:
#Creating a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.2805, 0.9429, 0.3308, 0.6358],
        [0.3512, 0.2794, 0.5661, 0.6615],
        [0.1892, 0.7414, 0.8278, 0.6912]])

In [ ]:
## both the tensor command gives the same output most of the time
some_tensor.size(),some_tensor.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [ ]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.size()}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.2805, 0.9429, 0.3308, 0.6358],
        [0.3512, 0.2794, 0.5661, 0.6615],
        [0.1892, 0.7414, 0.8278, 0.6912]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


### Manipulating Tensors (tensor operation)

Tensor operations include:
* Addition
* Substraction
* Multiplication(element-wise)
* Division
* Matrix multiplication

In [ ]:
# Creating a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# We didn't reassinged it so value is same
tensor

tensor([1, 2, 3])

In [ ]:
# Substract 10
tensor-10

tensor([-9, -8, -7])

In [ ]:
# Try out pytorch in-built function
torch.mul(tensor,10)

tensor([10, 20, 30])

In [ ]:
tensor = tensor + 10
print(tensor)
print(torch.add(tensor,10))
print(torch.sub(tensor,10))
print(torch.div(tensor,10))

tensor([11, 12, 13])
tensor([21, 22, 23])
tensor([1, 2, 3])
tensor([1.1000, 1.2000, 1.3000])


### Matrix multiplication

Two main waay of performing multiplication in neural network and deep learning:

1. Element-wise multiplication
2. Matrix multiplication(also called dot product)



In [ ]:
tensor = torch.tensor([1,2,3])

In [ ]:
# Element wise multiplication
print(tensor,"*",tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor,tensor)

# Dont amaze at the output of this multiplication(do it by your self on 3*4 and 4*5 matrix)

tensor(14)

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 1.43 ms, sys: 0 ns, total: 1.43 ms
Wall time: 1.25 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 334 µs, sys: 0 ns, total: 334 µs
Wall time: 263 µs


tensor(14)

##One of the most common error in deep learning :shape errors

In [ ]:
#shapes for matrix multiplication
tensor_A = torch.tensor([[1,2],[3,4],[5,6]])
tensor_B = torch.tensor([[7,10],[8,11],[9,12]])
torch.mm(tensor_A,tensor_B) # torch.mm is same as torch.matmul (it's an alias for writign less code)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

 To fix tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches teh axes or dimensions of a given tensor.

In [ ]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
torch.matmul(tensor_A,tensor_B.T),torch.matmul(tensor_A,tensor_B.T).shape


In [ ]:
# The matrix multiplication ooperation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above), tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min,max,mean,sum,etc(tensor aggregation)

In [2]:
#Create a  tensor
import torch
x = torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [6]:
# Find the min
torch.min(x),x.min()

(tensor(0), tensor(0))

In [7]:
#Find the max
torch.max(x),x.max()

(tensor(90), tensor(90))

In [9]:
#Find the mean
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [11]:
# Find the sum
torch.sum(x),x.sum()

(tensor(450), tensor(450))

## Finding the positoinal min and max

In [12]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
# find the position in tensor that has the minium value with argmin() -> returns index
x.argmin()

tensor(0)

In [14]:
x[0]

tensor(0)

In [15]:
x.argmax()

tensor(9)

In [16]:
x[9]

tensor(90)

## Reshapig,stacking ,squeezing and unsqueezing tensors

* Reshaping - reshpaes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shpae but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top ofeach other(vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target torch._test_check_tensor
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way


In [26]:
# Create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [7]:
# Add an extra dimension
# x_reshaped = x.reshape(1, 7)
# x_reshaped, x_reshaped.shape

In [28]:
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [29]:
# Change view (keeps same data as original but changes view)
# See more: https://stackoverflow.com/a/54507446/7900723
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [30]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [31]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

## Indexing

In [4]:
import torch
x = torch.arange(1,7).reshape(1,2,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6]]]),
 torch.Size([1, 2, 3]))

In [5]:
x[0,1,1]

tensor(5)

## PyTorch tesnors & NumPy


In [17]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numppy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [18]:
array.dtype,tensor.dtype

(dtype('float64'), torch.float64)

In [2]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [25]:
# Tensor to NumPy array
tensor_n = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor_n, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [26]:
# Change the tensor, keep the array the same
tensor_n = tensor_n + 1
tensor_n,tensor_n.dtype, numpy_tensor, numpy_tensor.dtype

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 torch.float32,
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32),
 dtype('float32'))


## Reproducibility (trying to take the random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> try to make better (again and again and again)`

To reduce the randomness in neural networks and pytorch comees the concept of a **random seed**.

Essentiall what the random seed does is "flavour: the randomness

In [28]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.1399, 0.0235, 0.6173, 0.0761],
        [0.5569, 0.9519, 0.2004, 0.7933],
        [0.9396, 0.3944, 0.3037, 0.3627]])

Tensor B:
tensor([[0.5512, 0.7779, 0.9469, 0.3049],
        [0.1785, 0.7475, 0.2923, 0.0825],
        [0.6862, 0.9139, 0.5995, 0.8083]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [1]:
# Let's make some randomm but reproducible tensors

import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Extra resources for reproducability-https://pytorch.org/docs/stable/notes/randomness.html

## Running tensors and PyTorch objects on the GPUs (and makiing faster compuytations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scene to make everything hunkydory(good).


### 1.Getting the GPU

1. Easiest - Use Google collab
2. Use your own GPU
3. Use cloud computing

### 2.Check for GPU access with PyTorch

In [2]:
# Chec for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

E.g. run on GPU if available, else default to CPU`

In [3]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [4]:
# Count number of devices
torch.cuda.device_count()

0

## 3.Putting tensors(and models) on the GPU
The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.


In [5]:
# Create a tensor(default on the CPU)
tensor = torch.tensor([1,2,3])

# Tensor not on GPU
print(tensor,tensor.device)

tensor([1, 2, 3]) cpu


In [6]:
# Move tensor to GPU(if available)
tesnor_on_gpu = tensor.to(device)
tensor_on_gpu

NameError: name 'tensor_on_gpu' is not defined

## 4. Moving tensors back to the CPU

In [7]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

NameError: name 'tensor_on_gpu' is not defined

In [ ]:
# To fix the GPU tensor with NumPy issue, we can frst set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu